framework:
    workflows: 
        candidate:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:    
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Candidate
            initial_marking: submitted
            places:
                - submitted
                - accepted
                - rejected
            transitions:
                accept:
                    from: submitted
                    to: accepted
                reject:
                    from: submitted
                    to: rejected            

